eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: INFO

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8000/users/current