spring:
#  h2:
#    console:
#      enabled: true
#      settings:
#              web-allow-others: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    initialization-mode: always

server:
  port: 8000




