server:
  port: 7000
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
          hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    initialization-mode: always
    url: jdbc:mysql://192.168.99.100:3306/gamedb
    username: app_user
    password: ${MYSQL_PASSWORD}

security:
  oauth2:
    client:
      clientId: database-service
      clientSecret: ${DATABASE_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:8000/oauth/token
      grant-type: client_credentials
      scope: server